### ISSUE TITLE
Bp Error

### ISSUE THREAD

**Issue by uruskan** [bw2012/UE5VoxelTerrainDemo#4]
The property associated with  Right Foot Rotator  could not be found in '/Game/Sandbox/Character/ALS/G8_ALS_AnimBP.G8_ALS_AnimBP_C'
![image](https://github.com/bw2012/UE5VoxelTerrainDemo/assets/12987255/6efdfef4-1a9b-406a-a9b3-a34033c4c1d5)

I don't have much experience with UE so I thought maybe this is about anim and these variables only exists when game is started but then I tried to build the game and it crashed the UE so I think there is a problem.

Is there a Discord channel or something for this project?

**Comment by bw2012** [comment]
Sorry, Content.zip was outdated. Please redownload Content.zip and unpack to project folder
